name: Build iOS App

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the workflow

jobs:
  build-ios:
    name: 🎉 Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable  # Use Flutter's stable channel

      - name: Install dependencies
        run: flutter pub get

      - name: Set up iOS simulator (optional)
        run: |
          sudo xcode-select -s /Applications/Xcode_12.5.app/Contents/Developer  # Set the correct Xcode version if needed
          sudo gem install cocoapods
          pod repo update
        working-directory: ios

      - name: Build iOS App (Release)
        run: flutter build ios --release --no-codesign
        working-directory: .

      - name: Find and Zip .app file
        run: |
          mkdir -p $GITHUB_WORKSPACE/app_output
          cp -r build/ios/iphoneos/Runner.app $GITHUB_WORKSPACE/app_output/
          cd $GITHUB_WORKSPACE/app_output && zip -r Runner.app.zip Runner.app
          
      - name: Upload the .app file to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: ios-app
          path: app_output/Runner.app.zip
